CarDealer/Models/Make.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations; //etiquetas

namespace CarDealer.Models
{
    public class Make
    {
        [Key] //sea llave primaria
        public int Id { get; set; }

        
        [DisplayName("Make Name")]
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }
       


    }
}

CarDealer/Areas/Admin/Controllers/MakeController.cs
using CarDealer.Data.Repository.Interfaces;
using CarDealer.Models;
using CarDealer.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace CarDealer.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CarDealerRoles.Role_Admin)]
    public class MakeController : Controller
    {

        private IUnitOfWork _unitOfWork;

        public MakeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var model = _unitOfWork.Make.GetAll().ToList(); // Obtener todas las entidades Make
            return View(model);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Make.Add(make);
                _unitOfWork.Save();
                TempData["success"] = "Make created successfully";
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Make.Update(make);
                _unitOfWork.Save();
                TempData["success"] = "Make updated successfully";
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null && id <= 0)
            {
                return NotFound();
            }

            Make? makeFromDb = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDb == null)
            {
                return NotFound();
            }
            return View(makeFromDb);
        }



        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null && id <= 0)
            {
                return NotFound();
            }

            Make? makeFromDb = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDb == null)
            {
                return NotFound();
            }
            return View(makeFromDb);
        }



        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Make? makeFromDB = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDB == null)
            {
                return NotFound();
            }

            _unitOfWork.Make.Remove(makeFromDB);
            _unitOfWork.Save();

            TempData["success"] = "Make deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CarDealer/Areas/Admin/Views/Make/Create.cshtml
@model Make

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary"> Create Make</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" class="form-control" />
            <div class="p-2">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-area="Admin" asp-controller="Make" asp-action="Index" style="width:150px" class="btn btn-secondary">Return to list</a>

    </div>

</form>

CarDealer/Areas/Admin/Views/Make/Delete.cshtml
@model Make

<form method="post">

    @* <input asp-for="Id" hidden /> *@

    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Make</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" readonly type="text" class="form-control"/>

            <div class="p-2">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-area="Admin" asp-controller="Make" asp-action="Index" style="width:150px" class="btn btn-secondary">Return to list</a>

    </div>
    
</form>

CarDealer/Areas/Admin/Views/Make/Edit.cshtml
@model Make


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Make</h2>
        </div>
        <div class="mb-3">
            <label asp-for="Name" class="p-0"></label>
            <input asp-for="Name" type="text" class="form-control"/>

            <div class="p-2">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>

        <button type="submit" class="btn btn-primary" style="width:150px">Save</button>
        <a asp-area="Admin" asp-controller="Make" asp-action="Index" style="width:150px" class="btn btn-secondary">Return to list</a>

    </div>
    
</form>

CarDealer/Areas/Admin/Views/Make/Index.cshtml
@model List<Make>

<partial name="_Notifications" />

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                List of vehicle makes
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-area="Admin" asp-controller="Make" asp-action="Create" class="btn btn-primary"> <i class="bi bi-plus-circle"></i> Create new make</a>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th> Make</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                @foreach (var obj in Model.OrderBy(x => x.Name))
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>
                            <div class="btn-group w-75" role="group">
                                <a asp-area="Admin" asp-controller="Make" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-area="Admin" asp-controller="Make" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                                    <i class="bi bi-trash"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="2" class="text-center">No data available</td>
                </tr>
            }
        </tbody>
    </table>
</div>