CarDealer/Areas/Admin/Controllers/MakeController.cs
using CarDealer.Data.Repository.Interfaces;
using CarDealer.Models;
using CarDealer.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace CarDealer.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CarDealerRoles.Role_Admin)]
    public class MakeController : Controller
    {

        private IUnitOfWork _unitOfWork;

        public MakeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var model = _unitOfWork.Make.GetAll().ToList(); // Obtener todas las entidades Make
            return View(model);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(Make make)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Make.Add(make);
                _unitOfWork.Save();
                TempData["success"] = "Make created successfully";
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Edit(Make make)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Make.Update(make);
                _unitOfWork.Save();
                TempData["success"] = "Make updated successfully";
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null && id <= 0)
            {
                return NotFound();
            }

            Make? makeFromDb = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDb == null)
            {
                return NotFound();
            }
            return View(makeFromDb);
        }



        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null && id <= 0)
            {
                return NotFound();
            }

            Make? makeFromDb = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDb == null)
            {
                return NotFound();
            }
            return View(makeFromDb);
        }



        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Make? makeFromDB = _unitOfWork.Make.Get(x => x.Id == id);

            if (makeFromDB == null)
            {
                return NotFound();
            }

            _unitOfWork.Make.Remove(makeFromDB);
            _unitOfWork.Save();

            TempData["success"] = "Make deleted successfully";
            return RedirectToAction("Index");

        }
    }
}

CarDealer/Areas/Admin/Controllers/VehicleController.cs
using CarDealer.Data.Repository.Interfaces;
using CarDealer.Models;
using CarDealer.Models.ViewModels;
using CarDealer.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarDealer.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CarDealerRoles.Role_Admin)]
    public class VehicleController : Controller
    {

        #region Properties_Constructor
        private readonly IUnitOfWork _unitOfWork;
        private IWebHostEnvironment _webHostEnvironment;

        public VehicleController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        #endregion

        #region HTTP_GET_POST

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            VehicleVM myModel = new()
            {
                Vehicle = new(),
                VehicleModelList = _unitOfWork.VehicleModel.GetAll(includeProperties: "Make").Select(i => new SelectListItem
                {
                    Text = i.Make.Name + " " + i.Name,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return View(myModel);
            }

            myModel.Vehicle = _unitOfWork.Vehicle.Get(x => x.Id == id);

            if (myModel.Vehicle == null)
            {
                return NotFound();
            }

            return View(myModel);
        }

        [HttpPost]
        public IActionResult Upsert(VehicleVM _vehicleVM, IFormFile? file)
        {
            if (ModelState.IsValid)
            {

                string wwwRootPath = _webHostEnvironment.WebRootPath;

                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    string extension = Path.GetExtension(file.FileName);
                    var uploads = Path.Combine(wwwRootPath, @"images\vehicles");

                    if (_vehicleVM.Vehicle.PictureUrl != null)// Update
                    {
                        var oldImageUrl = Path.Combine(wwwRootPath, _vehicleVM.Vehicle.PictureUrl);

                        if (System.IO.File.Exists(oldImageUrl))
                            System.IO.File.Delete(oldImageUrl);
                    }

                    using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }

                    _vehicleVM.Vehicle.PictureUrl = @"images\vehicles\" + fileName + extension;

                }


                if (_vehicleVM.Vehicle.Id == 0)
                    _unitOfWork.Vehicle.Add(_vehicleVM.Vehicle);
                else
                    _unitOfWork.Vehicle.Update(_vehicleVM.Vehicle);

                _unitOfWork.Save();
                TempData["success"] = "Vehicle saved successfully";
            }
            return RedirectToAction("Index");
        }

        #endregion

        #region API

        public IActionResult GetAll()
        {
            var vehicleList = _unitOfWork.Vehicle.GetAll(includeProperties: "Model,Model.Make");
            return Json(new { data = vehicleList });

        }

        public IActionResult Delete(int? id)
        {
            var vehicleToDelete = _unitOfWork.Vehicle.Get(x => x.Id == id);

            if (vehicleToDelete == null)
                return Json(new { success = false, message = "Error while deleting" });
            _unitOfWork.Vehicle.Remove(vehicleToDelete);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleted successfully" });

        }
        #endregion
    }
}

CarDealer/Areas/Admin/Controllers/VehicleModelController.cs
using CarDealer.Data.Repository.Interfaces;
using CarDealer.Models;
using CarDealer.Models.ViewModels;
using CarDealer.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CarDealer.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = CarDealerRoles.Role_Admin)]
    public class VehicleModelController : Controller
    {
        #region Properties_Constructor
        private readonly IUnitOfWork _unitOfWork;
        public VehicleModelController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        #endregion

        #region HTTP_GET_POST
        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            VehicleModelVM myModel = new VehicleModelVM();

            myModel.MakeList = _unitOfWork.Make.GetAll().Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });

            myModel.VehicleModel = new VehicleModel();

            if (id == null || id <= 0)
                return View(myModel);

            myModel.VehicleModel = _unitOfWork.VehicleModel.Get(x => x.Id == id);
            return View(myModel);

        }

        [HttpPost]
        public IActionResult Upsert(VehicleModelVM _vehicleModel)
        {
            if (ModelState.IsValid)
            {
                if (_vehicleModel.VehicleModel.Id == 0)
                    _unitOfWork.VehicleModel.Add(_vehicleModel.VehicleModel);
                else
                    _unitOfWork.VehicleModel.Update(_vehicleModel.VehicleModel);

                _unitOfWork.Save();
                TempData["success"] = "Model saved successfully";
            }
            else
            {
                TempData["error"] = "Error creating model";
            }
            return RedirectToAction("Index");
        }
        #endregion

        #region API
        [HttpGet]
        public IActionResult GetAll()
        {
            var modelList = _unitOfWork.VehicleModel.GetAll(includeProperties: "Make");
            return Json(new { data = modelList });
        }


        [HttpDelete]
        public IActionResult Delete(int? id)
        {

            //cargar modelo
            var modelToDelete = _unitOfWork.VehicleModel.Get(x => x.Id == id);

            if (modelToDelete == null)
                return Json(new { success = false, message = "Error while deleting" });

            _unitOfWork.VehicleModel.Remove(modelToDelete);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleted successfully" });

        }
        #endregion

    }
}

CarDealer/Views/Shared/_Layout.cshtml
@using CarDealer.Utilities

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDealer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarDealer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.7/css/dataTables.dataTables.min.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarDealer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
 
                          @if (User.IsInRole(CarDealerRoles.Role_Admin))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Menu</a>
                                <div class="dropdown-menu">

                                    <a class="dropdown-item text-light" asp-area="Admin" asp-controller="Make" asp-action="Index">Make</a>

                                    <div class="dropdown-divider"></div>

                                    <a class="dropdown-item text-light" asp-area="Admin" asp-controller="VehicleModel" asp-action="Index">VehicleModel</a>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-light" asp-area="Admin" asp-controller="Vehicle" asp-action="Index">Vehicle</a>

                                </div>
                            </li>
                        }
                    </ul>
                    <partial name ="_LoginPartial"></partial>>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Proyecto realizado en curso App Lenguajes; Melissa Molina - <i class="bi bi-chat-left-heart-fill"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.7/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <partial name="_ValidationScriptsPartial" />
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CarDealer/Views/Shared/_Notifications.cshtml
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Command: toastr["success"]("@TempData["success"]")

        toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": false,
            "progressBar": false,
            "positionClass": "toast-bottom-full-width",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Command: toastr["error"]("@TempData["error"]"")

                toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": false,
                "progressBar": false,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }
    </script>
}